import bcrypt from "bcryptjs";
import { ITenantConfig, IUser, ITransaction, IReward, INotification } from "./types";

export function seedInitialData() {
  const adminPasswordHash = bcrypt.hashSync("admin123", 10);

  const config: ITenantConfig = {
    _id: "config_cove_default",
    storeName: "Cove Coffee House",
    tagline: "Artisan Roastery & Specialty Brew Bar",
    logoUrl: "",
    primaryColor: "#2C221E",
    accentColor: "#1A5336",
    terracottaColor: "#C87D55",
    currency: "KWD",
    pointsPerUnit: 10,
    discountPer100Pts: 1.0,
    welcomeBonusPts: 50,
    updatedAt: new Date().toISOString(),
  };

  const users: IUser[] = [
    // Super Admin
    {
      _id: "admin_01",
      role: "super_admin",
      name: "Cove General Manager",
      email: "admin@covecoffee.com",
      passwordHash: adminPasswordHash,
      pointsBalance: 0,
      lifetimePoints: 0,
      tier: "Gold",
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    // Cashiers
    {
      _id: "cashier_01",
      role: "cashier",
      name: "Salem Al-Otaibi",
      username: "cashier1",
      staffPin: "1234",
      branchName: "Downtown Flagship",
      isActive: true,
      pointsBalance: 0,
      lifetimePoints: 0,
      tier: "Member",
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      _id: "cashier_02",
      role: "cashier",
      name: "Nour Al-Sabah",
      username: "cashier2",
      staffPin: "5678",
      branchName: "Marina Waterfront",
      isActive: true,
      pointsBalance: 0,
      lifetimePoints: 0,
      tier: "Member",
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    // Demo Customers (with Google Account Integration)
    {
      _id: "cust_01",
      role: "customer",
      name: "Tariq Al-Mansoor",
      email: "tariq@gmail.com",
      googleId: "google_tariq_01",
      phone: "+965 99112233",
      pin: "482910",
      qrSecret: "cove_token_tariq_482910",
      pointsBalance: 280,
      lifetimePoints: 640,
      tier: "Silver",
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
    {
      _id: "cust_02",
      role: "customer",
      name: "Deema Al-Kandari",
      email: "deema@gmail.com",
      googleId: "google_deema_02",
      phone: "+965 98765432",
      pin: "735194",
      qrSecret: "cove_token_deema_735194",
      pointsBalance: 520,
      lifetimePoints: 1150,
      tier: "Gold",
      createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    },
    {
      _id: "cust_03",
      role: "customer",
      name: "Fahad Al-Mutawa",
      email: "fahad@gmail.com",
      googleId: "google_fahad_03",
      phone: "+965 55443322",
      pin: "109482",
      qrSecret: "cove_token_fahad_109482",
      pointsBalance: 95,
      lifetimePoints: 150,
      tier: "Member",
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
  ];

  const transactions: ITransaction[] = [
    {
      _id: "tx_01",
      type: "EARN",
      customerId: "cust_01",
      customerName: "Tariq Al-Mansoor",
      customerPhone: "+965 99112233",
      cashierId: "cashier_01",
      cashierName: "Salem Al-Otaibi",
      branchName: "Downtown Flagship",
      billAmount: 4.5,
      points: 45,
      balanceAfter: 280,
      referenceCode: "TX-892147",
      notes: "V60 Ethiopian Yirgacheffe + Croissant",
      createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
    {
      _id: "tx_02",
      type: "REDEEM",
      customerId: "cust_01",
      customerName: "Tariq Al-Mansoor",
      customerPhone: "+965 99112233",
      cashierId: "cashier_01",
      cashierName: "Salem Al-Otaibi",
      branchName: "Downtown Flagship",
      points: -80,
      balanceAfter: 235,
      rewardTitle: "Artisan Flat White / Latte",
      referenceCode: "TX-773419",
      notes: "Reward Claim Voucher #RW-4821",
      createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    },
    {
      _id: "tx_03",
      type: "EARN",
      customerId: "cust_02",
      customerName: "Deema Al-Kandari",
      customerPhone: "+965 98765432",
      cashierId: "cashier_02",
      cashierName: "Nour Al-Sabah",
      branchName: "Marina Waterfront",
      billAmount: 12.0,
      points: 120,
      balanceAfter: 520,
      referenceCode: "TX-990142",
      notes: "Cold Brew Growler + 2x Specialty Sandwiches",
      createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    },
    {
      _id: "tx_04",
      type: "EARN",
      customerId: "cust_03",
      customerName: "Fahad Al-Mutawa",
      customerPhone: "+965 55443322",
      cashierId: "cashier_01",
      cashierName: "Salem Al-Otaibi",
      branchName: "Downtown Flagship",
      billAmount: 4.5,
      points: 45,
      balanceAfter: 95,
      referenceCode: "TX-441203",
      notes: "Spanish Latte + Cardamom Bun",
      createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    },
  ];

  const rewards: IReward[] = [
    {
      _id: "rew_01",
      title: "Artisan Flat White or Latte",
      description: "Any handcrafted espresso milk beverage of your choice with specialty house beans.",
      pointsRequired: 80,
      category: "Drinks",
      imageUrl: "/coffee-latte.svg",
      isActive: true,
      stock: 999,
      redemptionCount: 42,
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
    {
      _id: "rew_02",
      title: "Kyoto Style Cold Brew (16oz)",
      description: "18-hour slow-drip single origin batch served over artisanal crystal ice.",
      pointsRequired: 120,
      category: "Drinks",
      imageUrl: "/cold-brew.svg",
      isActive: true,
      stock: 999,
      redemptionCount: 28,
      createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    },
    {
      _id: "rew_03",
      title: "Freshly Baked Pistachio Croissant",
      description: "Twice-baked French butter croissant filled with rich Iranian pistachio cream.",
      pointsRequired: 90,
      category: "Food",
      imageUrl: "/croissant.svg",
      isActive: true,
      stock: 45,
      redemptionCount: 19,
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    },
    {
      _id: "rew_04",
      title: "20% Off Entire Ticket",
      description: "Instant 20% discount on your entire beverage & food order during your visit.",
      pointsRequired: 200,
      category: "Special",
      imageUrl: "/discount.svg",
      isActive: true,
      stock: 999,
      redemptionCount: 64,
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      _id: "rew_05",
      title: "House Blend 250g Whole Bean Bag",
      description: "Signature Cove blend (Notes of dark chocolate, hazelnut, and sweet fig).",
      pointsRequired: 350,
      category: "Beans",
      imageUrl: "/coffee-bag.svg",
      isActive: true,
      stock: 30,
      redemptionCount: 14,
      createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    },
    {
      _id: "rew_06",
      title: "Cove Matte Ceramic Travel Tumbler",
      description: "Double-walled ceramic insulated tumbler with leak-proof walnut lid.",
      pointsRequired: 500,
      category: "Merchandise",
      imageUrl: "/tumbler.svg",
      isActive: true,
      stock: 12,
      redemptionCount: 8,
      createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    },
  ];

  const notifications: INotification[] = [
    {
      _id: "notif_01",
      customerId: "all",
      title: "Welcome to Cove Loyalty",
      message: "Present your QR code or 6-digit PIN at the register to earn 10 points on every 1.000 KWD spent!",
      type: "BROADCAST",
      isRead: false,
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    },
    {
      _id: "notif_02",
      customerId: "cust_01",
      title: "Points Credited! +45 Points",
      message: "You just earned 45 points on your order at Downtown Flagship. Your balance is 280 points.",
      type: "POINTS_EARNED",
      isRead: false,
      createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
    {
      _id: "notif_03",
      customerId: "cust_02",
      title: "Points Credited! +120 Points",
      message: "You just earned 120 points at Marina Waterfront. Keep brewing!",
      type: "POINTS_EARNED",
      isRead: true,
      createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    },
  ];

  return { config, users, transactions, rewards, notifications };
}
